# Pour désactiver un sign, merci de placer un "false"
# Dans le cas contraire le plugin rechargera la valeur par défaut

# Sign = la phrase doit débuter par ce signe, inclure le signe entre quote (' ') pour eviter les erreurs.
# Radius = la portée en cube
# Prefix = Poser un prefix avant le nom du joueur et la phrase, false pour retirer (pas de règles, les parenthèses sont ma mise en forme, à vous d'adapter !
# Color = la couleur de l'ensemble du message, utilisez les codes couleurs de Minecraft, '&f' pour blanc, '&0' pour noir etc, ne paso ublier les quotes ' '.
# Codes couleurs: http://www.minecraftwiki.net/wiki/Formatting_codes (utilisez un & et pas un §
# server-flood et world-flood définissent le temps minimum entre 2 messages (en secondes) pour le chan world et server

#SI VOUS VOULEZ DESACTIVER UNE COMMANDE, mettre le sign sur false aucun besoin de toucher au reste.

# Mode realiste
# Définit le nombre de cube supplémentaires par rapport au radius de base, dans lesquels la personne
# entendra des "bruits" sans capter la conversation, attention ceci est un pourcentage 5 = 5%, 20 = 10%, ne pas rajouter le % :)
# Mettre le radius a 0 desactive
real-radius: 20
real-anonym: false

# Chuchoter
whisp-sign: '*'
whisp-radius: 5
whisp-prefix: (Chuchoter)
whisp-color: '&d'
# Parler localement
local-radius: 20
local-prefix: false
local-color: '&f'
# Crier
shout-sign: '!'
shout-radius: 60
shout-prefix: (Crier)
shout-color: '&e'
# Hors roleplay
hrp-sign: '('
hrp-radius: 20
hrp-prefix: (Hrp)
hrp-color: '&7'
# Chat pour le World actuel
world-sign: '@'
world-prefix: (Monde)
world-color: '&9'
world-flood: 3
# Chat pour tout le serveur
server-sign: '='
server-prefix: (Serveur)
server-color: '&2'
server-flood: 3

